server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /favicon.ico {
        try_files $uri =404;
    }

    location /favicon.svg {
        try_files $uri =404;
    }

    location /favicon.png {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
   
    # # Uncomment for local Docker Compose backend proxy
    # location /api/ {
    # proxy_pass http://app:8000/api/;
    # proxy_set_header Host $host;
    # proxy_set_header X-Real-IP $remote_addr;
}
}